//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCBTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;columns&quot;: [
        ///    {
        ///      &quot;code&quot;: &quot;Region&quot;,
        ///      &quot;text&quot;: &quot;region&quot;,
        ///      &quot;type&quot;: &quot;d&quot;
        ///    },
        ///    {
        ///      &quot;code&quot;: &quot;Tid&quot;,
        ///      &quot;text&quot;: &quot;valår&quot;,
        ///      &quot;type&quot;: &quot;t&quot;
        ///    },
        ///    {
        ///      &quot;code&quot;: &quot;ME0104B8&quot;,
        ///      &quot;text&quot;: &quot;Valdeltagande i riksdagsval, procent&quot;,
        ///      &quot;type&quot;: &quot;c&quot;
        ///    }
        ///  ],
        ///  &quot;comments&quot;: [
        ///    {
        ///      &quot;variable&quot;: &quot;Foobar&quot;,
        ///      &quot;value&quot;: &quot;1900&quot;,
        ///      &quot;comment&quot;: &quot;Foobar&quot;
        ///    }
        ///  ],
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;key&quot;: [ &quot;00&quot;, &quot;1900&quot; ],
        ///      &quot;values&quot;: [ &quot;00.0&quot; ]
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string ValidParticipationResult {
            get {
                return ResourceManager.GetString("ValidParticipationResult", resourceCulture);
            }
        }
    }
}
